name: .NET Core

on:
   push:
    branches:
    - master

jobs:
  linux:      
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
      - name: Setup
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100
      - name: Build
        run: dotnet build './src/NMS.Leo/Leo.csproj' -f net5.0 --configuration Release
      - name: Test
        run: dotnet test './test/NCallerUT'
     
  windows:
      runs-on: windows-latest
      steps:
       - uses: actions/checkout@v1
       - name: Setup
         uses: actions/setup-dotnet@v1
         with:
          dotnet-version: 5.0.100
       - name: Build
         run: dotnet build './src/NMS.Leo/Leo.csproj' -f net5.0 --configuration Release
       - name: Test
         run: dotnet test './test/NCallerUT'
   
  mac:
      runs-on: macos-latest
      steps:
      - uses: actions/checkout@v1
      - name: Setup
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100
      - name: Build
        run: dotnet build './src/NMS.Leo/Leo.csproj' -f net5.0 --configuration Release
      - name: Test
        run: dotnet test './test/NCallerUT'
